- handlr-regex/src/apps/mod.rs
- handlr-regex/src/apps/regex.rs
- handlr-regex/src/apps/user.rs
Moves regex handlers to a field in `MimeApps` rather than having a separate global instance. Fixes #20.
> Refactor regex handlers to better fit pre-existing conventions

- README.md
- handlr-regex/src/common/desktop_entry.rs
- handlr-regex/src/config.rs
Adds config file option, `term_exec_args` to config file to configure what arguments are passed to terminal emulator when running `handlr get --json` for a terminal program when not in a terminal. Fixes #7
> Add option to configure arguments passed to terminal emulator

- handlr-regex/src/common/ini.pest
The [spec for mimetypes.list](https://specifications.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html#default) doesn't seem to forbid the value of an association/default application to be the empty string.
Either way, I think `handlr-regex` should be able to tolerate a `mimetypes.list` that has such lines. For example, with a `mimetypes.list` file like this:
```
[Default Applications]
text/plain=
```
launching the program results in a panic:
```shell
$ handlr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: ParseApps(Error { variant: ParsingError { positives: [value_char], negatives: [] }, location: Pos(34), line_col: Pos((2, 12)), path: None, line: "text/plain=␊", continued_line: None }) }', handlr-regex/src/apps/user.rs:16:65
note: run with …
```
> Allow empty associations

- Cargo.lock
- handlr-regex/src/apps/user.rs
Fixes `cargo build` failure from dep `proc-macro2` not exposing methods
`before()` and `after()` needed for feature `proc_macro_span_shrink`.
```
error[E0635]: unknown feature `proc_macro_span_shrink`
--> /home/sam/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.52/src/lib.rs:92:30
|
92 |     feature(proc_macro_span, proc_macro_span_shrink)
|                              ^^^^^^^^^^^^^^^^^^^^^^
```
> Fix build by updating dependencies & fix panic on receiving `mimeapps.list` with lines with no handlers.

- Cargo.lock
- README.md
- assets/manual/man1/handlr-get.1
- assets/manual/man1/handlr-list.1
- assets/manual/man1/handlr.1
- handlr-regex/Cargo.toml
- handlr-regex/src/apps/user.rs
- handlr-regex/src/cli.rs
- handlr-regex/src/common/mod.rs
- handlr-regex/src/common/path.rs
- handlr-regex/src/common/table.rs
- handlr-regex/src/error.rs
- handlr-regex/src/main.rs
Various changes related to json and table output:
- Add `--json` to `handlr list` (Solves #46)
- Replace `json` with `serde_json` to take advantage of the `Serialize` trait.
- Replace `ascii_table` with `tabled` to solve the issue with truncated table output mentioned in #46 and to take advantage of the `Tabled` trait.
- Tweak formatting of table output to help with legibility for larger outputs.
- If a subcommand with tabular output is being piped, format the table(s) as tab-separated values to add another option for using output.
> Overhaul json and table output

- Cargo.lock
- assets/manual/man1/handlr-add.1
- assets/manual/man1/handlr-get.1
- assets/manual/man1/handlr-launch.1
- assets/manual/man1/handlr-list.1
- assets/manual/man1/handlr-mime.1
- assets/manual/man1/handlr-open.1
- assets/manual/man1/handlr-remove.1
- assets/manual/man1/handlr-set.1
- assets/manual/man1/handlr-unset.1
- assets/manual/man1/handlr.1
- handlr-regex/Cargo.toml
- handlr-regex/src/cli.rs
- handlr-regex/src/common/mime_types.rs
- handlr-regex/src/common/path.rs
- xtask/Cargo.toml
- xtask/src/main.rs
Uses clap's `#[clap(verbatim_doc_comment)]` derive attribute so that json snippets do not get messed up by preprocessing.
Also updates clap to take advantage of fixes that simplify `cargo xtask mangen`'s implementation.
Resolves #15.
> Fix manpage json snippets and simplify manpage rendering

- README.md
`handlr-regex` is now on the official `extra` repo, replacing the original unmaintained project.
> Source:
> https://archlinux.org/packages/extra/x86_64/handlr-regex/
> docs: update `ArchLinux`'s installation instructions

- README.md
Documentation change that I've mentioned in #53
> [DOC] Shadow xdg-open instead of xdg-utils-handlr usage (#53)

- Cargo.lock
Update libc to v0.2.155 to support loongarch64.
Release notes: https://github.com/rust-lang/libc/releases.
> Update Cargo.lock: fix build on loongarch64

- Cargo.lock
- handlr-regex/Cargo.toml
- handlr-regex/src/common/mime_types.rs
- handlr-regex/tests/no_html_tags.html
Updates `xdg-mime` to 0.4.0 to fix bug with improper file type detection and adds regression tests.
Closes #56
> fix: properly detect html files with no html tags

- assets/manual/man1/handlr-get.1
- assets/manual/man1/handlr-launch.1
- assets/manual/man1/handlr-open.1
- handlr-regex/src/apps/user.rs
- handlr-regex/src/cli.rs
- handlr-regex/src/common/desktop_entry.rs
- handlr-regex/src/common/handler.rs
- handlr-regex/src/config.rs
- handlr-regex/src/main.rs
Adds `--selector`, `--enable-selector`, and `--disable-selector` flags to `handlr get`, `handlr open`, and `handlr launch`, the three subcommands that use the selector and updated manpages accordingly.
Closes #60
> feat: add flags to override the selector options in the config file

- Cargo.lock
- README.md
- handlr-regex/Cargo.toml
- handlr-regex/src/apps/user.rs
- handlr-regex/src/config/main_config.rs
Adds the ability to use wildcards for mimetypes other than having the entire subtype be wild.
For instance, now all of the OpenDocument formats can be matched with `application/vnd.oasis.opendocument.*` without also matching all of the other mimetypes under `application`.
> feat: add more flexible wildcards

- Cargo.lock
- Cargo.toml
- src/apps/system.rs
- src/apps/user.rs
- src/config/main_config.rs
- src/main.rs
- tests/mimeapps_no_added.list
- tests/mimeapps_no_default.list
- tests/mimeapps_sorted.list
Fixes a regression discussed in #68: If there is no `[Added Associations]` or `[Default Applications]` section in `mimeapps.list`, `handlr` will wipe `mimeapps.list` if one runs a subcommand that edits it (e.g. `handlr set`). Also fortunately closes #69.
Also fixes other regressions I noticed while fixing the above:
- The `mimeapps.list` and `handlr.toml` files both get ignored in favor of default values if either are missing.
- The associations in `mimeapps.list` get saved in a random order after editing it with `handlr`.
In addition, adds regression tests for the above problems where applicable and has some minor refactoring.
> fix: regressions related to editing mimeapps.list

- src/common/desktop_entry.rs
- src/common/mime_types.rs
Fixes an issue with opening terminal applications discussed in #68 and discarding `application/x-zerosize` mimetypes in #47.
I could not add a reliable regression test for the issue regarding opening terminal applications, because of issues with how fetching the command from the `x-scheme-handler/terminal` handler currently. Namely, issues with how it sets a handler if there is none. I intend to rework this behavior later.
> fix: bugs mentioned in discussions #68 and #47

- src/apps/user.rs
- src/cli.rs
- src/common/desktop_entry.rs
- src/common/handler.rs
- src/config/config_file.rs
- src/config/main_config.rs
- src/config/mod.rs
- src/main.rs
Mainly makes the logic for the selector-related flags reusable and DRY and avoids passing down selector options rather than passing state using a struct.
> refactor: clean up selector options implementation

- src/common/handler.rs
- src/config/main_config.rs
Fixes #76.
Apparently, the handlers were getting hashed based on what kind of handler they were (i.e. `DesktopHandler` vs. `RegexHandler`), so when using a HashMap to assign files to their respective handlers, they ended up all getting sorted to the same handler and causing issues.
> Fix issue with opening multiple files of different types

- src/apps/user.rs
> fix: use a line feed, not a carriage return at the end of the file

- src/apps/user.rs
- src/common/desktop_entry.rs
- src/common/handler.rs
- src/common/mime_types.rs
- src/common/path.rs
- src/config/main_config.rs
- src/error.rs
- src/main.rs
Stop ignoring config errors. Also ensures system notifications are issued for config errors when `handlr` is not run in a terminal and does some minor refactoring.
Fixes #82
> fix: do not ignore config errors

- build/apps.rs
- src/cli.rs
- src/config/main_config.rs
- src/main.rs
Fixes broken completions for some subcommands.
Hopefully also obviates the need for downstream maintainers to patch generated completion scripts.
Closes #89.
> fix: fix faulty completions

- flake.nix
Changes `defaultPackages` to `packages.${system}.default` because the former is deprecated.
Also adds some missing tools to the devshell.
Fixes #99
> chore: update package and shell declarations in flake
